engines:
  phpmd:
    enabled: true
    checks:
          Controversial/CamelCasePropertyName:
            enabled: false
  phpcodesniffer:
    enabled: true
  duplication:
      enabled: true
      config:
        languages:
        - php:

ratings:
  paths:
  - "organization/**/*"
  - "public/**/*"
  - "rxn/**/*"
  - "**.php"