engines:
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      Naming/LongVariable:
        enabled: false
  phpcodesniffer:
    enabled: true
  duplication:
      enabled: true
      config:
        languages:
        - php:

ratings:
  paths:
  - "organization/**/*"
  - "public/**/*"
  - "rxn/**/*"
  - "**.php"
